language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq byacc
install:
  - make
before_script:
  - cd tests
  - ./prepare.sh
script:
  - ./run_all.sh ../dsh | python3 check.py
after_script:
  - ./clean.sh
  - cd ..

