language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq byacc
install:
  - make
before_script:
  - cd tests
  - mkdir bin
  - make
  - ./prepare.sh
script:
  - echo -en 'travis_fold:start:running_tests\\r'
  - ./run_all.sh ../dsh >>result 2>&1
  - cat result
  - echo -en 'travis_fold:end:running_tests\\r'
  - cat result | python3 check.py
after_script:
  - ./clean.sh
  - cd ..

